### ISSUE TITLE
HW3 P1-C

### ISSUE THREAD

**Issue by winstonwzhang** [winstonwzhang/ecgannotate#6]
My GUI will store all user-added annotations for different sections of the ECG time series. The stored data format will be a list of dictionaries, with each dictionary containing the start time index, end time index, and annotation type. 

**[{'start': 23, 'end': 48, 'type': 'AF'}, {'start': 49, 'end': 75, 'type': VT}]**

For example, the list above contains two user-added annotations indicating the presence of AF (atrial fibrillation) and VT (ventricular tachycardia) at the time index periods (23, 48) and (49, 75) respectively.

Please add a function that will 

1. sort the user-added annotations by starting index
2. remove identical annotations (same start, end, and type)
3. merge annotations that are the same type if they overlap with each other in the time domain.

For example,

**[{'start': 23, 'end': 48, 'type': 'AF'}, {'start': 45, 'end': 75, 'type': AF}]**

Will be merged into

**[{'start': 23, 'end': 75, 'type': 'AF'}]**

------

Function requirements:

- Function name: sortMergeAnnotations
- Coding Language: Python
- Input: Annotation list of dictionaries
- Output: Sorted and merged annotation list

**Comment by PersimmonPPP** [comment]
Commit ID: [41d99ad](https://github.com/winstonwzhang/ecgannotate/pull/7/commits/41d99ad8eb562bb4f74b560cac4b886f1ba099a6)
Implementation finished. Please check the pull request.

**Comment by winstonwzhang** [comment]
Good job, thanks for the function!
